In [121]:
# Linear Algebra - Example

In [122]:
import numpy as np #import libraries
from numpy import linalg as LA
from sympy import Matrix

In [123]:
A = np.matrix([[0, 0, 0], [1, 0, 2], [0, 1, 1]]) #define A matrix
print(A)

[[0 0 0]
 [1 0 2]
 [0 1 1]]


In [124]:
E,T = LA.eig(A) # E = eigenvalues T = eigenvectors

In [125]:
print(E)

[ 2. -1.  0.]


In [126]:
print(T)

[[ 0.          0.          0.81649658]
 [ 0.70710678  0.89442719  0.40824829]
 [ 0.70710678 -0.4472136  -0.40824829]]


In [127]:
T = np.matrix(T) # T -> matrix class
Tinv = np.matrix(LA.inv(T))
print(Tinv)

[[ 0.23570226  0.47140452  0.94280904]
 [-0.74535599  0.74535599 -0.74535599]
 [ 1.22474487  0.          0.        ]]


In [128]:
print(T*Tinv)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [ -1.66533454e-16   5.55111512e-17   1.00000000e+00]]


In [129]:
Adiag = Tinv*A*T

In [130]:
print(Adiag)

[[  2.00000000e+00  -1.11022302e-16   0.00000000e+00]
 [  0.00000000e+00  -1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]]


In [131]:
B = np.array([[0, 4, 3], [0, 20, 16], [0, -25, -20]]) #define B matrix
B = Matrix(B)

In [132]:
print(B.eigenvals())

{0: 3}


In [133]:
P, J = B.jordan_form() # P = transformation matrix J = Jordan matrix

In [134]:
print(P)

Matrix([[10.2500000000000, 8.00000000000000, 0], [0, 41.0000000000000, 1.25000000000000], [0, -51.2500000000000, 1]])


In [135]:
print(J)

Matrix([[0, 1, 0], [0, 0, 1], [0, 0, 0]])
